global using System;
global using System.Collections;
global using System.Collections.Generic;
global using System.Linq;
global using HarmonyLib;
global using UnityEngine;
global using static UnityEngine.Object;
global using Object = UnityEngine.Object;
global using Random = UnityEngine.Random;
global using ScriptableObject = UnityEngine.ScriptableObject;
global using JFUtils;
global using static JFUtils.ModBase;
global using static Heightmap;
global using static Heightmap.Biome;
global using static ItemDrop;
global using static TotemsOfUndying.Plugin;
global using static Skills;
global using JetBrains.Annotations;
global using TMPro;